### ISSUE TITLE
ValueError: labels [0] not contained in axis in 

### ISSUE THREAD

**Issue by hmkim** [sequana/sequana#175]
Hi, 

When I use the sequana for Kraken data, I got the error in below.

Please check this.

```
import sys
sys.path.append('/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/sequana/')

from sequana import  KrakenResults, KrakenAnalysis, KrakenDownload


if __name__ == "__main__":
    test_file = '/BiO/Contamination/S0001'
    k = KrakenResults(test_file, verbose=False)
    df = k.plot(kind='pie')
    print(df)
    k.to_js(onweb=False)
```

```
Snakemake must be installed. Available for Python3 only
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    df = k.plot(kind='pie')
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/sequana/kraken.py", line 250, in plot
    self.kraken_to_krona()
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/sequana/kraken.py", line 181, in kraken_to_krona
    taxon_to_find = list(self.taxons.index)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/sequana/kraken.py", line 166, in _get_taxons
    self._parse_data()
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/sequana/kraken.py", line 149, in _parse_data
    self._taxons.drop(0, inplace=True)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 1873, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/pandas/indexes/base.py", line 2966, in drop
    labels[mask])
ValueError: labels [0] not contained in axis
```

**Comment by cokelaer** [comment]
Hi,
To help us debugging your issue, could you please provide a sample of your input file named '/BiO/Contamination/S0001' ?
thanks

**Comment by hmkim** [comment]
https://www.dropbox.com/s/6g5rk1cxrcj6tu5/example_data.tar.bz2?dl=0

15MB (real size is about 162MB)

Thanks
