### ISSUE TITLE
problem with copying of multiqc.yaml on rnaseq pipeline

### ISSUE THREAD

**Issue by rlegendre** [sequana/sequana#319]
Copying snakefile
Creating README
Creating the config file
copied config.yaml from sequana rnaseq pipeline
Traceback (most recent call last):
  File "/pasteur/homes/rlegendr/.conda/envs/py35/bin/sequana", line 11, in <module>
    load_entry_point('sequana', 'console_scripts', 'sequana')()
  File "/pasteur/projets/policy01/Biomics/Dev/Rachel/sequana/sequana/scripts/main.py", line 595, in main
    sequana_init(options)
  File "/pasteur/projets/policy01/Biomics/Dev/Rachel/sequana/sequana/scripts/main.py", line 688, in sequana_init
    copy_config_from_sequana(module, "config.yaml", config_filename)
  File "/pasteur/projets/policy01/Biomics/Dev/Rachel/sequana/sequana/scripts/main.py", line 613, in copy_config_from_sequana
    shutil.copy(multiqc_config, options.target_dir + os.sep + "multiqc_config.yaml")
NameError: name 'options' is not defined

**Comment by ddesvillechabrol** [comment]
1d9d3ed
Fixed

**Comment by ddesvillechabrol** [comment]
17348b4
Fixed.
