### ISSUE TITLE
rulegraph and dag rules with new temporary directory seem to have random errors

### ISSUE THREAD

**Issue by cokelaer** [sequana/sequana#335]
Seems to be related to a directory not being created quickly enough ? 
Indeed, when we start again (directory is now created), there is no errors

Solution: remove temp directory creation and use a local directory (dag/ and rulegraph/)

**Comment by cokelaer** [comment]
Fixed. The dag rule is not required anymore (only rulegraph makes sense). 
I updated the snakemake pipelines accordingly (rna, variant, quality).

**Comment by rlegendre** [comment]
Traceback (most recent call last):
  File "/pasteur/homes/rlegendr/.conda/envs/py35/lib/python3.5/site-packages/snakemake/__init__.py", line 420, in snakemake
    force_use_threads=use_threads)
  File "/pasteur/homes/rlegendr/.conda/envs/py35/lib/python3.5/site-packages/snakemake/workflow.py", line 480, in execute
    success = scheduler.schedule()
  File "/pasteur/homes/rlegendr/.conda/envs/py35/lib/python3.5/site-packages/snakemake/scheduler.py", line 215, in schedule
    self.run(job)
  File "/pasteur/homes/rlegendr/.conda/envs/py35/lib/python3.5/site-packages/snakemake/scheduler.py", line 237, in run_cluster_or_local
    error_callback=self._error)
  File "/pasteur/homes/rlegendr/.conda/envs/py35/lib/python3.5/site-packages/snakemake/executors.py", line 507, in run
    jobscript = self.get_jobscript(job)
  File "/pasteur/homes/rlegendr/.conda/envs/py35/lib/python3.5/site-packages/snakemake/executors.py", line 416, in get_jobscript
    self.tmpdir,
  File "/pasteur/homes/rlegendr/.conda/envs/py35/lib/python3.5/site-packages/snakemake/executors.py", line 411, in tmpdir
    self._tmpdir = mkdtemp(dir=".snakemake", prefix="tmp.")
  File "/pasteur/homes/rlegendr/.conda/envs/py35/lib/python3.5/tempfile.py", line 368, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '.snakemake/tmp.fd14trh8'
snakemake -s /pasteur/projets/specific/PF2_ngs/volatile/2017/170127_D00395_0296_BCA1NEANXX/SLX222-Namy/bioinf/analysis_test/rnaseq.rules --dag --nolock > dag.dot
