### ISSUE TITLE
sequana_coverage - division by 0

### ISSUE THREAD

**Issue by chrisBiomics** [sequana/sequana#416]
Traceback (most recent call last):
  File "/pasteur/projets/policy01/Matrix/conda/bin/sequana_coverage", line 11, in <module>
    load_entry_point('sequana==0.2.1', 'console_scripts', 'sequana_coverage')()
  File "/pasteur/projets/policy01/Matrix/conda/lib/python3.5/site-packages/sequana-0.2.1-py3.5.egg/sequana/scripts/coverage.py", line 286, in main
    run_analysis(chrom, options)
  File "/pasteur/projets/policy01/Matrix/conda/lib/python3.5/site-packages/sequana-0.2.1-py3.5.egg/sequana/scripts/coverage.py", line 309, in run_analysis
    print(chrom)
  File "/pasteur/projets/policy01/Matrix/conda/lib/python3.5/site-packages/sequana-0.2.1-py3.5.egg/sequana/bedtools.py", line 494, in __str__
    stats = self.get_stats(output="dataframe")
  File "/pasteur/projets/policy01/Matrix/conda/lib/python3.5/site-packages/sequana-0.2.1-py3.5.egg/sequana/bedtools.py", line 1083, in get_stats
    stats['CV'] = stats['STD'] / stats['DOC']
ZeroDivisionError: float division by zero

**Comment by cokelaer** [comment]
should be fixed on the develop branch
