### ISSUE TITLE
Broken PyQt5 dependency (conda@macOS)

### ISSUE THREAD

**Issue by simonepignotti** [sequana/sequana#531]
Hi,
I am trying to use `sequanix` on mac, using the conda install method. I run into the following error while trying to launch it:
```
(sequana_env) $ sequanix
Traceback (most recent call last):
  File "/Users/simonepignotti/.conda/envs/sequana_env/lib/python3.5/site-packages/sequana/gui/browser.py", line 6, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView as QWebView
ImportError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/simonepignotti/.conda/envs/sequana_env/bin/sequanix", line 7, in <module>
    from sequana.gui.sequana_gui import main
  File "/Users/simonepignotti/.conda/envs/sequana_env/lib/python3.5/site-packages/sequana/gui/sequana_gui.py", line 30, in <module>
    from sequana.gui.browser import Browser
  File "/Users/simonepignotti/.conda/envs/sequana_env/lib/python3.5/site-packages/sequana/gui/browser.py", line 18, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ImportError: No module named 'PyQt5.QtWebKitWidgets'
```
To create the environment, I used the very same commands as in sequana's docs, making sure my channels have the right priority.
These are the Qt versions installed by conda:
```
pyqt:                     5.6.0-py35h8210e8a_7    conda-forge
qt:                       5.6.2-hd4c90f3_9        conda-forge
qtconsole:                4.4.2-py_1              conda-forge
```

Have you encountered this issue already? Is it possible to downgrade PyQt to a functioning version?
Thank you in advance for your time!

**Comment by ddesvillechabrol** [comment]
Hi !

I tried it on a Mac and I had the same trouble.
To fix it, I installed the pyqt from conda default channel:
`conda install -c defaults pyqt=5 qt`
Could you try ?

Thanks !
Dimitri

**Comment by simonepignotti** [comment]
Hi Dimitri,
Thanks a lot, that worked. Should I close the issue or leave it open till pyqt gets updated on `conda-forge`?
For information, the following packages were affected by the switch to `defaults`:
```
$ conda install -n sequana_env -c defaults pyqt=5 qt
Solving environment: done

## Package Plan ##

  environment location: /Users/simonepignotti/.conda/envs/sequana_env

  added / updated specs:
    - pyqt=5
    - qt


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    dbus-1.13.2                |       h5243cc1_0         540 KB  defaults
    glib-2.53.6                |       h33f6a65_2         4.8 MB  defaults
    ------------------------------------------------------------
                                           Total:         5.3 MB

The following NEW packages will be INSTALLED:

    dbus:            1.13.2-h5243cc1_0     defaults
    gettext:         0.19.8.1-h15daf44_3   defaults
    glib:            2.53.6-h33f6a65_2     defaults

The following packages will be UPDATED:

    pyqt:            5.6.0-py35h8210e8a_7  conda-forge --> 5.9.2-py35h655552a_2  defaults
    qt:              5.6.2-hd4c90f3_9      conda-forge --> 5.9.6-h45cd832_2      defaults
    sip:             4.18.1-py35hfc679d8_0 conda-forge --> 4.19.8-py35h0a44026_0 defaults

The following packages will be DOWNGRADED:

    ca-certificates: 2018.10.15-ha4d7672_0 conda-forge --> 2018.03.07-0          defaults
    certifi:         2018.8.24-py35_1001   conda-forge --> 2018.8.24-py35_1      defaults
    openssl:         1.0.2p-h470a237_1     conda-forge --> 1.0.2p-h1de35cc_0     defaults
```

Simone

**Comment by simonepignotti** [comment]
Great, thanks a lot!

Simone
