### ISSUE TITLE
Possible issue in sequama_pipetools when using the --from-project

### ISSUE THREAD

**Issue by cokelaer** [sequana/sequana#669]
sequana_ribofinder --from-project ribofinder --working-directory ribofinder2
WARNING [sequana]: With --from-project option, pipeline and data-related options will be ignored.
WARNING [sequana_pipetools.snaketools.sequana_config:96]:  You should use a YAML file with .yaml or .yml extension
Traceback (most recent call last):
  File "/home/cokelaer/Work/github/forked/sequana_pipetools/sequana_pipetools/snaketools/sequana_config.py", line 74, in __init__
    self.config = AttrDict(**data)
TypeError: type object argument after ** must be a mapping, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cokelaer/miniconda3/envs/sequana/bin/sequana_ribofinder", line 33, in <module>
    sys.exit(load_entry_point('sequana-ribofinder', 'console_scripts', 'sequana_ribofinder')())
  File "/home/cokelaer/Work/github/sequana_pipelines/ribofinder/sequana_pipelines/ribofinder/main.py", line 104, in main
    manager = SequanaManager(options, NAME)
  File "/home/cokelaer/Work/github/forked/sequana_pipetools/sequana_pipetools/sequana_manager.py", line 83, in __init__
    self.config = SequanaConfig(filename)
  File "/home/cokelaer/Work/github/forked/sequana_pipetools/sequana_pipetools/snaketools/sequana_config.py", line 84, in __init__
    config = self._read_file(data)
  File "/home/cokelaer/Work/github/forked/sequana_pipetools/sequana_pipetools/snaketools/sequana_config.py", line 100, in _read_file
    with open(data, "r") as fh:
IsADirectoryError: [Errno 21] Is a directory: 'ribofinder'

**Comment by cokelaer** [comment]
Fixed in sequana_pipetools 0.7.1
